### ISSUE TITLE
broken example for HTTP-EQUIV <meta> tag?

### ISSUE THREAD

**Issue by ssbertilson** [leejo/CGI.pm#175]
From the perldoc:
And here's how to create an HTTP-EQUIV <meta> tag:

    print start_html(-head=>meta({-http_equiv => 'Content-Type',
                             -content => 'text/html'}))

Throwing this into a script at at perl (v5.14.2):
use strict;
use CGI;
my $cgi = CGI->new();
print $cgi->header();
print start_html(-head=>meta({-http_equiv => 'Content-Type',
                 -content => 'text/html'}));
results in:
Content-Type: text/html; charset=ISO-8859-1

Undefined subroutine &main::meta called at CGI-test.pl line 7.

How can I make this work?
(My objective is to do a http_equiv/refresh.)

**Comment by sjohnston** [comment]
This example assumes you are using the functional-style. Since your 
script is using the OO-style, you need to update the call to do the same:

print $cgi->start_html(-head=> $cgi->meta(...

**Comment by leejo** [comment]
Yep, as @sjohnston says you're mixing the functional and OO interfaces. If you want the functional interface you need to import the required functions using `use CGI qw/ :foo /`. It's a good idea to stick with just one interface, and IMO the OO interface since internally CGI.pm will just create a default object if you don't.

I'm working on the docs at the moment, to make them more consistent, although this is a slow process.

**Comment by leejo** [comment]
Oh, and as an aside: i would really really *really* try to avoid using any of the HTML generation functions. I plan to kill them off eventually.
