### ISSUE TITLE
Programmatic HTML generation - alternatives and future

### ISSUE THREAD

**Issue by epa** [leejo/CGI.pm#188]
I may be the only one, but I rather like the programmatic HTML generation with `p()`, `table()` and so on.  This may be because my use of CGI.pm is for in-house reports, typically only a few hundred lines of Perl code, rather than for "web development".  Anyway, I understand that the HTML generation in CGI.pm is a bit of a mess and on the way out.  But I was surprised to find nothing in `CGI::Alternatives` that replaces it with compatible functionality.

This seems a bit daft, since surely every programmer in the year 2015 knows that templating systems exist; if the programmer has chosen to hand-generate HTML with function calls rather than using a templating system then that is surely a deliberate choice.  It is like suggesting the use of Perl instead of assembly language - yes, there are many problems that can be tackled in either language, but they are not exactly alternatives.

Anyway, I can see `HTML::TagTree` on CPAN which could be worth a mention, although this too isn't quite comparable because it requires you to generate the whole tree before outputting anything.  (For my uses at least, it is important to be able to print a partial page which can be seen by the user immediately and then add more text later.)  `HTML::Table` is specialized for tables but again, doesn't seem to support incremental output.  Do you know of any others?

`HTML::Entities` is worth a mention as an alternative for `escapeHTML()`.

Rather than just eliminating HTML generation in a future version, I suggest it too could be kicked out into a separate module.  As with other things, that could be included as a dependency for a transitional period and then dropped.

**Comment by leejo** [comment]
As per the [contributing](https://github.com/leejo/CGI.pm/blob/master/CONTRIBUTING.md) file: `HTML functionality in the module - these methods are considered deprecated. There will be no changes to them or pull requests accepted for them no matter how trivial.`

I'm leaving the HTML functionality in the module, but letting it rot. I won't be splitting out the functionality as this will annoy too many users, and i won't be doing any maintenance because i don't want to give the impression that this functionality is acceptable in a modern web app: it's not.

You should separate your business logic and presentation layer, even if you're working with trivial hundred line scripts. [This](https://github.com/leejo/cgi-alternatives/blob/master/examples/templates/example_form.html.tt) will render in your browser without having to be processed, and is much easier to debug / modify / update. And if/when you decided to migrate to something other than CGI.pm your presentation layer needs minimal changes to work with a newer framework.

HTML::Entities is already used internally by CGI.pm, this is mentioned in the perldoc:

```
    $escaped_string = escapeHTML("unescaped string");
        Escape HTML formatting characters in a string. Internally this calls
        HTML::Entities (encode_entities) so really you should just use that
        instead
```

**Comment by epa** [comment]
I agree, it is not acceptable in a modern web app.  But not all CGI scripts are modern web apps, and many do not aspire to be.  The main use case for CGI.pm, IMHO, is rather like the classic use of Perl itself: gluing together disparate bits and pieces and presenting a usable interface to them with minimal fuss.  I worked as a web developer back in the day, using template systems, and there's no way I would want to be without them.  But equally there are plenty of cases where they get in the way.

If the HTML generation is staying in the module then I guess that works.  I was worried it would be suddenly removed in a future version.

**Comment by leejo** [comment]
No no, it's staying in the module.

**Comment by epa** [comment]
The perldoc isn't quite clear: "will continue to exist in the v4 releases of CGI.pm but may be deprecated (soft) in v5 and beyond".  Aren't they deprecated already?  If so what is the different thing that might start happening in v5 and beyond?

**Comment by leejo** [comment]
Yes, they're deprecated already in the sense that they're not being maintained. There won't be any deprecation warnings however.

**Comment by epa** [comment]
Thanks for the clarification.  Could I suggest a change in wording:

Documentation for these functions has been moved to L<CGI::HTML::Functions>.  They will continue to exist in CGI.pm.  Although their use is discouraged, there will not be any deprecation warnings.

**Comment by epa** [comment]
Ah I see you got there before me, thx.
