### ISSUE TITLE
%QUERY_PARAM is not cleared

### ISSUE THREAD

**Issue by billmoseley** [leejo/CGI.pm#201]
initialize_globals() doesn't undef %QUERY_PARAM, and that is called under mod_perl in a cleanup handler.  The result is file uploads leak and are not cleaned up.

save_request() saves to %QUERY_PARAM.

Is the code too old and crusty for `use strict;` and `use warnings;`?

**Comment by leejo** [comment]
Thanks, v4.28 on its way to CPAN.

> Is the code too old and crusty for use strict; and use warnings;?

I have a [branch](https://github.com/leejo/CGI.pm/tree/lee/fix_warnings) for `use warnings` that i haven't looked at in a while and would like to get out perhaps as a later version, but i'm in two minds about it

  * will start to fill people's logs with warnings (already had grumbles about that in the past)
  * possibly a breaking change for anyone mad enough to have enabled fatal warnings (by themselves or, for example, an older version of Moo)
  * any cleanup of warnings i do will probably introduce a bug or two no matter how careful i am and i'm probably not going to cover all the variations of calling that could raise warnings
  * doesn't gain us much other than lots of work for lots more bugs
  * will no doubt have to litter the code with `no warnings 'redefine'` and other such exceptions
  * because the code needs to support earlier perls i can't use nice things such as `//` to fix warnings
  * probably other issues.

As for `use strict` - again i'd like to but the code is nowhere near a state to make it run under strict so will need lots of changes to do so, again possibly introducing bugs, etc, etc. `use strict` and `use warnings` are long term goals.
