### ISSUE TITLE
Bad test plan for t/request.t if Test::Deep is not available

### ISSUE THREAD

**Issue by ppisar** [leejo/CGI.pm#202]
Since CGI-4.27, t/reqest.t fails if Test::Deep is not installed:

~~~
ok 42 - url_param keywords
ok 43 # skip Test::Deep module is not available
ok 44 # skip Test::Deep module is not available
ok 45 # skip Test::Deep module is not available
# Looks like you planned 44 tests but ran 45.
~~~

This is because wrong change in t/request.t between 4.26 and 4.27:

~~~
--- CGI-4.26/t/request.t        2016-03-15 12:33:18.276874633 +0100
+++ CGI-4.27/t/request.t        2016-03-15 12:33:11.340839202 +0100
@@ -3,7 +3,7 @@
 use strict;
 use warnings;
 
-use Test::More tests => 45;
+use Test::More tests => 44;
 
 use CGI ();
 use Config;
@@ -118,7 +118,7 @@
 
        SKIP: {
                skip 'Test::Deep module is not available', 3 unless
-                   (eval 'use Test::Deep 0.11; 1' && eval 'use Test::NoWarnings; 1');
+                   (eval 'use Test::Deep 0.11; 1');
                $^W++;
 
                CGI::_reset_globals;
~~~

You stopped loading Test::NoWarnings, so you decreased tests number from 45 to 44, but you forgot to decrease the skip number from 3 to 2 in 'Test::Deep module is not available' skip.

**Comment by leejo** [comment]
Where are you getting this version of `t/request.t` from? The version in the repo does not have a SKIP block, nor has it ever had one. Besides, Test::Deep is a requirement in the Makefile.PL so if you're building this distribution properly you should be told about the missing dependency (there are a few tests that require Test::Deep and none of them in the repo will skip the tests if is not installed). This was the actual change between 4.26 and 4.27:

```
*/Users/leejohnson/working/CGI.pm > git log -p --follow v4.26..v4.27 -- t/request.t
commit 66c02344dfd960b4be79901944ced00d2d310729
Author: Lee Johnson <lee@givengain.ch>
Date:   Wed Mar 2 08:49:11 2016 +0100

    fix a couple of warnings in test harness

    and skip if Test::Warn is not found for t/param_list_context.t as
    for some reason, even though this is in the Makefile.PL, some of
    the reports on cpantesters.org show it failing due to this module
    not being installed

    bump Version and Changes for CPAN release

diff --git a/t/request.t b/t/request.t
index 2c5974d..114b852 100644
--- a/t/request.t
+++ b/t/request.t
@@ -3,9 +3,8 @@
 use strict;
 use warnings;

-use Test::More tests => 45;
+use Test::More tests => 44;
 use Test::Deep;
-use Test::NoWarnings;

 use CGI ();
 use Config;
```

Is this a vendor supplied package? If so the bug is with them and not here, because they have a propensity to faff around in the distribution and not send patches upstream.

**Comment by jplesnik** [comment]
The skip section is part of Fedora change, which is used during mass rebuild. The Fedora's patch has to be updated.

**Comment by leejo** [comment]
@jplesnik - thanks! Closing.

If any vendor perl package managers are reading: please send patches like this upstream.

**Comment by ppisar** [comment]
I'm sorry. I did not verified that was a Fedora patch. It was needed when CGI was a dual-lived module in order to update CGI from CPAN without non-core modules. Because recent Perl does not bundle CGI, the patch will be removed from the Fedora. For your reference, the corrected patch is <http://pkgs.fedoraproject.org/cgit/rpms/perl-CGI.git/tree/CGI-4.28-Make-Test-Deep-tests-optional.patch>.

**Comment by leejo** [comment]
@ppisar - thanks. I'm not going to apply that patch because the tests are there for a very good reason, skipping them is not an option IMO. If Fedora users want to install CGI.pm (or run its tests) then they'll have to install Test::Deep beforehand, or Fedora will have to ensure that their package management system makes sure to install Test::Deep as a prerequisite of running the distribution's test suite.
