### ISSUE TITLE
Remove dependency on CGI.pm in high river CPAN dists.

### ISSUE THREAD

**Issue by leejo** [leejo/CGI.pm#250]
Template and WWW::Mechanize https://metacpan.org/module/CGI/requires?sort=[[0,1]] - these alone are probably responsible for CGI.pm being installed on many boxes that don't really need it.

**Comment by cschwenz** [comment]
I can second this request.

The Template module is how I had CGI foisted upon my system. :-D

Looking into why Template uses this module, https://metacpan.org/release/ATOOMIC/Template-Toolkit-3.010/source/Makefile.PL#L155 is the offending line (it only needs it for testing).

Also, checking out https://metacpan.org/module/CGI/requires?sort=[[3,1]] it appears like, for whatever reason, in 2019 there was a resurgence of use/interest in the CGI module (if you use uploads of other modules which use CGI in some capacity as the metric).

As odd as it sounds, that resurgence in usage is likely due to https://github.com/leejo/CGI.pm/commit/98126c6ca2087fba268a43c1e61d6d9add53347a clarifying who holds the copyright and making explicit what the license is.

**Comment by leejo** [comment]
Thanks Cal. Looking in a bit more detail, the Template2 dist uses CGI.pm in `Template::Plugin::CGI` and the test of that module. So while it only appears to be required by testing, there is harder requirement by one of the modules in the dist.

A solution might be to split `Template::Plugin::CGI` into its own dist, but that might break downstream darkpan given the history here. Not sure what @toddr and @atoomic think? There are still a few issues related to CGI.pm in the Template2 dist (e.g. https://github.com/abw/Template2/issues/212 and https://github.com/abw/Template2/issues/215) so getting it split out *might* be something worth doing.

**Comment by leejo** [comment]
Also https://github.com/libwww-perl/WWW-Mechanize/pull/327 removes CGI.pm from WWW::Mechanize. Looking at https://metacpan.org/module/CGI/requires?sort=[[0,1]] CGI.pm is no longer required by any high river dists 🎉 

Closing.
